apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-spring-to-access-cluster
subjects:
  - kind: ServiceAccount
    name: spring-service-account
roleRef:
  kind: ClusterRole
  name: spring-roles
  apiGroup: rbac.authorization.k8s.io
