apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-mysql-configmap
data:
  spring.datasource.url: "jdbc:mysql://mysql-helm-service:3306/task_manager_db?allowPublicKeyRetrieval=true&&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-redis-configmap
data:
  spring.redis.host: "redis-helm-service-master"
  spring.redis.port: "6379"
  spring.cache.redis.time-to-live: "30000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-rabbitmq-configmap
data:
  spring.rabbitmq.host: "rabbitmq-helm-service"
  spring.rabbitmq.port: "5672"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-mail-configmap
data:
  spring.mail.host: "smtp.gmail.com"
  spring.mail.port: "587"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-thread-pool-configmap
data:
  spring.task.execution.pool.core-size: "10"
  spring.task.execution.pool.max-size: "30"
  spring.task.execution.pool.queue-capacity: "40"
