apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  spring.datasource.database: "task_manager_db"
  spring.datasource.url: "jdbc:mysql://mysql-service:3306/task_manager_db?allowPublicKeyRetrieval=true&&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  spring.data.mongodb.host: "mongo-service"
  spring.data.mongodb.port: "27017"
  spring.data.mongodb.database: "audit_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  spring.redis.host: "redis-service"
  spring.redis.port: "6379"
  spring.cache.redis.time-to-live: "30000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
data:
  spring.rabbitmq.host: "rabbitmq-service"
  spring.rabbitmq.port: "5672"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-configmap
data:
  spring.mail.host: "smtp.gmail.com"
  spring.mail.port: "587"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thread-pool-configmap
data:
  spring.task.execution.pool.core-size: "10"
  spring.task.execution.pool.max-size: "30"
  spring.task.execution.pool.queue-capacity: "40"
