apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  mysql_database: "task_manager_db"
  mysql_datasource_url: "jdbc:mysql://mysql-service:3306/task_manager_db?allowPublicKeyRetrieval=true&&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  mongo_host: "mongo-service"
  mongo_port: "27017"
  mongo_database: "audit_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  redis_host: "redis-service"
  redis_port: "6379"
  redis_cache_ttl: "30000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
data:
  rabbitmq_host: "rabbitmq-service"
  rabbitmq_port: "5672"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-configmap
data:
  mail_host: "smtp.gmail.com"
  mail_port: "587"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thread-pool-configmap
data:
  thread_pool_core_size: "10"
  thread_pool_async_max_size: "30"
  thread_pool_queue_capacity: "40"
