apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  spring.datasource.username: bXlzcWxfdXNlcm5hbWU=
  spring.datasource.password: Ny5VXVU6WUY/di1RK20uVA==

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  spring.data.mongodb.username: bW9uZ29fdXNlcm5hbWU=
  spring.data.mongodb.password: eXs8UTchXlRKLD50KjgsNQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: mail-credentials-secret
data:
  spring.mail.username: dGVzdGphdmFtYWlsc2VuZDJAZ21haWwuY29t
  spring.mail.password: dGVzdF9qYXZhX21haWxfc2VuZA==
